"""empty message

Revision ID: 6385a5ad23ea
Revises: d913b8891e1b
Create Date: 2017-11-14 18:33:08.750051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6385a5ad23ea'
down_revision = 'd913b8891e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index', sa.Column('C', sa.Float(), nullable=True))
    op.add_column('index', sa.Column('C1', sa.Float(), nullable=True))
    op.add_column('index', sa.Column('C2', sa.Float(), nullable=True))
    op.add_column('index', sa.Column('C3', sa.Float(), nullable=True))
    op.add_column('index', sa.Column('E', sa.Float(), nullable=True))
    op.add_column('index', sa.Column('E1', sa.Float(), nullable=True))
    op.add_column('index', sa.Column('E2', sa.Float(), nullable=True))
    op.add_column('index', sa.Column('E3', sa.Float(), nullable=True))
    op.add_column('index', sa.Column('I', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index', 'I')
    op.drop_column('index', 'E3')
    op.drop_column('index', 'E2')
    op.drop_column('index', 'E1')
    op.drop_column('index', 'E')
    op.drop_column('index', 'C3')
    op.drop_column('index', 'C2')
    op.drop_column('index', 'C1')
    op.drop_column('index', 'C')
    # ### end Alembic commands ###
