"""empty message

Revision ID: 9563ded706c5
Revises: 
Create Date: 2017-11-09 14:24:27.928755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9563ded706c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schoolName', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Date(), nullable=False),
    sa.Column('schoolProvince', sa.String(length=50), nullable=True),
    sa.Column('schoolCity', sa.String(length=50), nullable=True),
    sa.Column('schoolCounty', sa.String(length=50), nullable=True),
    sa.Column('schoolStu', sa.Float(), nullable=True),
    sa.Column('schoolPut', sa.Float(), nullable=True),
    sa.Column('studentAvg', sa.Integer(), nullable=True),
    sa.Column('computerSum', sa.Integer(), nullable=True),
    sa.Column('multiClass', sa.Integer(), nullable=True),
    sa.Column('classSum', sa.Integer(), nullable=True),
    sa.Column('broadband', sa.Float(), nullable=True),
    sa.Column('broadbandAvg', sa.Float(), nullable=True),
    sa.Column('effectPrepare', sa.Float(), nullable=True),
    sa.Column('pertinencePrepare', sa.Float(), nullable=True),
    sa.Column('optimizeTeach', sa.Float(), nullable=True),
    sa.Column('turnoverTeach', sa.Float(), nullable=True),
    sa.Column('manageCourse', sa.Float(), nullable=True),
    sa.Column('communicateCourse', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('identity', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('person_add',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('index_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['index_id'], ['index.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_add')
    op.drop_table('user')
    op.drop_table('index')
    # ### end Alembic commands ###
