"""empty message

Revision ID: d913b8891e1b
Revises: 9563ded706c5
Create Date: 2017-11-13 11:22:10.780391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd913b8891e1b'
down_revision = '9563ded706c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index', sa.Column('final_index', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'index', ['schoolName'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'index', type_='unique')
    op.drop_column('index', 'final_index')
    # ### end Alembic commands ###
